"""empty message

Revision ID: 1ad62f4d54d2
Revises: 4498e38c7d60
Create Date: 2023-02-22 14:32:56.971613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1ad62f4d54d2'
down_revision = '4498e38c7d60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whiskey', schema=None) as batch_op:
        batch_op.alter_column('date_acquired',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whiskey', schema=None) as batch_op:
        batch_op.alter_column('date_acquired',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###
